added members section
houseofgeeks/hg pull request #193
Opened 2020-10-28 20:37 UTC by hariom1625

### fixes #173 

Description: Added members section.

PS: I have added dummy info since I didn't have all the required details, will update it soon.
#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [ ] I've tested my code on Mozilla Firefox.
- [ ] My code gave a clean console on debugging. (no warnings/errors)

2020-10-28 20:41 UTC, ankiiitraj commented
I see a lot of code 😨

2020-10-28 20:46 UTC, hariom1625 commented
> I see a lot of code 😨

There were already different components made for different communities so enduring that further, I tried to keep the files and details for different communities separate so it got a bit lengthy 😅

2020-10-28 20:48 UTC, ankiiitraj commented
No issues! Great work btw!

2020-10-30 17:57 UTC, EmperorYP7 commented
Whats the progress on this? Do we have the details of all members?

2020-10-31 09:23 UTC, hariom1625 commented
> Whats the progress on this? Do we have the details of all members?

Not yet, maybe till tomorrow, I will try to add the details of all the members.

2020-11-02 10:23 UTC, hariom1625 commented
The PR can be reviewed now.
I have updated the details of most of the members and the remaining details we can add on the go.
Also,I am not able to figure out how to render the Github logo only for those members who have an account. If anyone has any idea can share or we can put up an issue for the same.

2020-11-02 12:26 UTC, EmperorYP7 requested changes
Very well done @hariom1625! :rocket: Just a few minor tweaks.

2020-11-02 12:26 UTC, EmperorYP7 commented on client/src/components/Members/Community/Head.members.js
> +                  Community Members
I think "Members" will be more relevant here. "Community Members" doesnt look good in mobile view anyways. Afterall, the main title should be according to the navbar.

2020-11-02 12:26 UTC, EmperorYP7 commented on client/src/components/Members/Community/Head.members.css
> +      font-size: 3rem;
With reference to #198 and #204, change the font-size to be `6vh`.

2020-11-02 19:44 UTC, devansh-srivastav-kashyap commented
Over-all, the website look appealing. Good work.

Put Joint Secretary just below Secretary.
Faculty is to be replaced by Faculty in Charge- Student Welfare

2020-11-02 20:23 UTC, ankiiitraj commented
> Over-all, the website look appealing. Good work.
> 
> Put Joint Secretary just below Secretary.
> Faculty is to be replaced by Faculty in Charge- Student Welfare

Or put Joint Sec beside the Sec?

2020-11-03 17:31 UTC, hariom1625 commented
@ankiiitraj and @devansh-srivastav-kashyap Which layout is being finalized?

2020-11-03 17:46 UTC, devansh-srivastav-kashyap commented
Website me toh ek k neeche ek hai na?

2020-11-03 17:46 UTC, devansh-srivastav-kashyap commented
Atleast in mobile, ek ke neeche ek hai.. toh in reference of mobile view, put j sec just below Secretary

2020-11-03 19:25 UTC, ankiiitraj commented
How about adding a border like this? @hariom1625 
![Screenshot from 2020-11-04 00-54-34](https://user-images.githubusercontent.com/48787278/98031377-65366e80-1e38-11eb-80a5-a86d0444bfac.png)

2020-11-03 19:31 UTC, ankiiitraj approved these changes
LGTM 🎉 
Very neat work!

2020-11-03 19:31 UTC, ankiiitraj commented on client/src/components/Members/Community/Event.members.js
> +// import {ReactComponent as Github} from "../img/github-brands.svg";
cleanup required!

2020-11-03 19:31 UTC, ankiiitraj commented on client/src/components/Members/Community/EventMembersList.js
> +            // github: '',
unnecssary comments needs to be removed before merging

2020-11-03 19:46 UTC, hariom1625 commented
> How about adding a border like this? @hariom1625
This looks great !! Will add the border in the next commit :-)

2020-11-04 10:46 UTC, tusharjain0022 approved these changes
Beautiful 🤩 , Nice Work @hariom1625 🙌

2020-11-04 13:21 UTC, EmperorYP7 approved these changes
This is super clean code. Nice work @hariom1625! 🥳

2020-11-04 13:22 UTC, EmperorYP7 commented
Merging this against all reviewers' approval.

2020-11-04 13:22 UTC, merged