Positions updated
houseofgeeks/hg pull request #254
Opened 2022-04-14 07:29 UTC by Abhinav200207

### Fixes #<number>
<Do not delete this template>
Description: <provide a description> The title should be short and relevant.

#### Checklist
- [ ] I've followed the Contributing guidelines provided in the repository.
- [ ] I've made the changes which were demanded in the linked issue.
- [ ] I've tested my code on a Chromium based browser.
- [ ] I've tested my code on Mozilla Firefox.
- [ ] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

2022-04-14 11:57 UTC, SrijanSriv requested changes
Thanks for updating the members @Abhinav200207 .

You might want to check out the deployment preview on different screens like a phone. There are some css related aspects that may also be cleared. 
Also, try to maintain a hierarchy. The coordinators go side by side, all below the head; for each community.

2022-05-13 06:24 UTC, SrijanSriv approved these changes
LGTM. Thanks a lot @Abhinav200207 :whale:

2022-05-13 06:27 UTC, merged

2022-05-13 10:13 UTC, EmperorYP7 commented on client/src/components/Members/Community/WebDAppD.members.js
> +                  Core Electronics Community Members
Change it to `Software Development Wing`

2022-06-01 15:15 UTC, 0548929024 reviewed
![21B64D89-F3FB-4E0E-9FD7-FE93D482DA7D](https://user-images.githubusercontent.com/106662209/171439034-717e6b2a-7ee1-4dae-934f-c03136a4cacc.jpeg)